### ISSUE TITLE
Sub-task9: Thermal image analysis for early disease detection

### ISSUE THREAD

**Issue by hydrotekfarm** [HydroTekFarm2023/hydro-ai-usecases#13]
In GitLab by @nivedita2293 on Nov 3, 2020, 08:33

## Overview/Problem Statement
Analysis of thermal images of plants like lettuce for early detection of any infections or diseases in the crop.

## Requirements

- [x] Analysis of thermal image using PlantCV.
- [x] Finding the area infected with color hue present in the image.
- [x] Identify the color, does it contain any red or yellow color.
- [x] Once classified, find the area of each color.
- [x] Find the intensity of each color.
- [x] Build REST API Service
- [ ] Make a secure API using certificates.
- [x] Build a microservice  using Docker
- [x] Integrate with the google cloud
- [x] Deploy a Kubernetes cluster

### Differ to next release
- [ ] Map the color and intensity with the type of disease.
- [ ] Map the disease with the treatment.

## TODO Task
- [x] To download the Thermal images from GCP (Cloud Object Storage).
- [x] Using PlantCV Algorithm detect if the plant is healthy or Unhealthy.
- [x] The processed output should be displayed on the console in JSON format.
- [x] Persist that result in MongoDB Collection.

### Date - 24-Nov-20
- [x] To check if the leaves have a yellow or red color.

## References
- The Application of Thermal Imaging to Biological Sciences
https://spierssciencetalk.wordpress.com/2015/08/06/the-application-of-thermal-imaging-to-biological-sciences/
- Thermal Image 
https://www.researchgate.net/figure/Thermal-images-of-healthy-cucumber-leaves-upper-and-leaves-inoculated-with-FOC-lower_fig3_232719555/
- Color Identification in Images
https://towardsdatascience.com/color-identification-in-images-machine-learning-application-b26e770c4c71
