### ISSUE TITLE
Automation of Data Gathering of Plant Images

### ISSUE THREAD

**Issue by hydrotekfarm** [HydroTekFarm2023/hydro-ai-usecases#14]
In GitLab by @bharathreddy1997 on Nov 27, 2020, 09:53

## Overview
Provide end to end automation of gathering the images from internet for the specific plant and disease.

## Requirements

- [ ] Fetching images from search engines.
- [ ] Filtering the images.
- [ ] Crop and Mask the images.
- [ ] Create a restful API.
- [ ] Building a secure rest API using Certs.
- [ ] Creating a microservice.
- [ ] Integrate Google Cloud.
- [ ]Deploying a Kubernetes cluster.
## Design and Implementation 
 -[ ] workflow diagram
## TODO Task

Read about the restful API and create a workflow diagram
